{
  Type: Exception,
  Message: The prefix has already been used. Existing: Tests.ThrowOnConflict. New: Tests.ThrowOnConflict. This is mostly caused by a conflicting combination of `VerifierSettings.DerivePathInfo()`, `UseMethodName.UseDirectory()`, `UseMethodName.UseTypeName()`, and `UseMethodName.UseMethodName()`. Prefix: {ProjectDirectory}CustomDir/CustomTypeName.Conflict,
  StackTrace: 
at FileNameBuilder.GetPrefix()
at FileNameBuilder..ctor(MethodInfo method, Type type, String projectDirectory, String sourceFile, IReadOnlyList`1 parameters, VerifySettings settings)
at VerifyTests.InnerVerifier..ctor(String sourceFile, Type type, VerifySettings settings, MethodInfo method, IReadOnlyList`1 parameters)
at VerifyXunit.Verifier.GetVerifier(VerifySettings settings, String sourceFile)
at VerifyXunit.Verifier.<>c__DisplayClass1_0.<<Verify>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at VerifyTests.SettingsTask.<>c__DisplayClass3_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at VerifyTests.InnerVerifier.ThrowsAsync(Func`1 target)
}