{
  Type: Exception,
  Message: The Message,
  StackTrace: 
at Tests.ValueTaskMethodThatThrows()
at VerifyTests.InnerVerifier.<ThrowsAsync>d__28.MoveNext()
}