{
  Type: Exception,
  Message: The Message,
  StackTrace:
at Tests.TaskMethodThatThrows()
at InnerVerifier.<ThrowsTask>d__37.MoveNext()
}