{
  Type: Exception,
  Message: The Message,
  StackTrace: 
at Tests.TaskMethodThatThrows()
at VerifyTests.InnerVerifier.<ThrowsAsync>d__29.MoveNext()
}