{
  Type: AggregateException,
  InnerExceptions: [
    {
      Type: Exception,
      Message: The Message1
    },
    {
      Type: Exception,
      Message: The Message2
    }
  ],
  Message: One or more errors occurred.,
  StackTrace: 
at Tests.MethodThatThrowsAggregate()
at VerifyTests.InnerVerifier.Throws(Action target)
}